server:
  port: 8081

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:3000/eureka/
#      instance:
#        prefer‐ip‐address: true #可以跨域访
#  instance:
#    instance-id: goods
#    prefer-ip-address: true #是否显示IP地址
#    leaseRenewalIntervalInSeconds: 10 #eureka客户需要多长时间发送心跳给eureka服务器，表明它仍然活着,默认为30 秒 (与下面配置的单位都是秒)
#    leaseExpirationDurationInSeconds: 30 #Eureka服务器在接收到实例的最后一次发出的心跳后，需要等待多久才可以将此实例删除，默认为90秒
spring:
  application:
    name: mall-goods

#ribbon:
#  ConnectTimeout: 1000 #服务请求连接超时时间（毫秒）
#  ReadTimeout: 3000 #服务请求处理超时时间（毫秒）
#  OkToRetryOnAllOperations: true #对超时请求启用重试机制
#  MaxAutoRetriesNextServer: 1 #切换重试实例的最大个数
#  MaxAutoRetries: 1 # 切换实例后重试最大次数
#  NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule #修改负载均衡算法

#eureka:
#  client: #eureka客户端配置
#    register-with-eureka: true #是否将自己注册到eureka服务端上去
#    fetch-registry: true #是否获取eureka服务端上注册的服务列表
#    service-url:
#      defaultZone: http://localhost:8001/eureka/ # 指定注册中心地址
#    enabled: true # 启用eureka客户端
#    registry-fetch-interval-seconds: 30 #定义去eureka服务端获取服务列表的时间间隔
#  instance: #eureka客户端实例配置
#    lease-renewal-interval-in-seconds: 30 #定义服务多久去注册中心续约
#    lease-expiration-duration-in-seconds: 90 #定义服务多久不去续约认为服务失效
#    metadata-map:
#      zone: jiangsu #所在区域
#    hostname: localhost #服务主机名称
#    prefer-ip-address: false #是否优先使用ip来作为主机名
#  server: #eureka服务端配置
#    enable-self-preservation: false #关闭eureka服务端的保护

