server:
  port: 3000
eureka:
  server:
    enable-self-preservation: false  #关闭自我保护机制
    eviction-interval-timer-in-ms: 4000 #设置清理间隔（单位：毫秒 默认是60*1000）
  instance:
    hostname: eureka
  client:
    registerWithEureka: false #不把自己作为一个客户端注册到自己身上
    fetchRegistry: false  #不需要从服务端获取注册信息（因为在这里自己就是服务端，而且已经禁用自己注册了）
    service-url:
      defaultZone: http://localhost:3000/eureka/
spring:
  application:
    name: eureka-server

#eureka:
#  client: #eureka客户端配置
#    register-with-eureka: true #是否将自己注册到eureka服务端上去
#    fetch-registry: true #是否获取eureka服务端上注册的服务列表
#    service-url:
#      defaultZone: http://localhost:8001/eureka/ # 指定注册中心地址
#    enabled: true # 启用eureka客户端
#    registry-fetch-interval-seconds: 30 #定义去eureka服务端获取服务列表的时间间隔
#  instance: #eureka客户端实例配置
#    lease-renewal-interval-in-seconds: 30 #定义服务多久去注册中心续约
#    lease-expiration-duration-in-seconds: 90 #定义服务多久不去续约认为服务失效
#    metadata-map:
#      zone: jiangsu #所在区域
#    hostname: localhost #服务主机名称
#    prefer-ip-address: false #是否优先使用ip来作为主机名
#  server: #eureka服务端配置
#    enable-self-preservation: false #关闭eureka服务端的保护机制

