server:
  port: 8089
  tomcat:
    uri-encoding: UTF-8
eureka:
  client:
    service-url:
      defaultZone: http://eureka:3000/eureka/
      instance:
        prefer‐ip‐address: true #可以跨域访
  instance:
    instance-id: web

spring:
  application:
    name: mall-web
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://116.62.223.130:3306/dolphinscheduler?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&autoReconnectForPools=true&useSSL=false&serverTimezone=Hongkong&allowMultiQueries=true
    username: root
    password: wj@123..
mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.mall.entity
