server:
  port: 8089
  tomcat:
    uri-encoding: UTF-8
eureka:
  client:
    service-url:
      defaultZone: http://localhost:3000/eureka/
      instance:
        prefer‐ip‐address: true #可以跨域访
  instance:
    instance-id: web


spring:
  http:
    encoding:
      charset: utf-8
      force: true
  application:
    name: wj-web
#  datasource:
#    driver-class-name: oracle.jdbc.driver.OracleDriver
#    url: jdbc:oracle:thin:@192.0.0.50:1521:orcl
#    username: dwy_db_test3
#    password: dwy_db_test3pass
mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.mall.entity
  mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

management:
  endpoints:
    web:
      exposure:
        include: '*'

logging:
  file: D://test/test.log
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger- %msg%n'
    file: '%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger- %msg%n'
